### ISSUE TITLE
Class not found error

### ISSUE THREAD

**Issue by kiangj** [zendesk/zendesk_api_client_php#188]
Using composer to include dev-master, when I updated to 52bdc2cf257febeab237edc7ce01d5fdecba6e2a, suddenly it causes a Zendesk\API\Client class not found.  Changed composer.json to install dev-master#7177ef7 and it's working again.

**Comment by jwswj** [comment]
@kiangj a lot has changed since https://github.com/zendesk/zendesk_api_client_php/compare/7177ef7...52bdc2c
The master branch is now a rewrite of the client and tagged as v2. You might want to lock your composer file down to 1.*
```
{
    "require": {
        "zendesk/zendesk_api_client_php": "1.*"
    }
}
```
More details can be found in the v2 PR: https://github.com/zendesk/zendesk_api_client_php/pull/99

**Comment by jwswj** [comment]
For others who might get the same error. If you've upgraded and are seeing:
```
Fatal error: Class 'Zendesk\API\Client' not found
```
then you have probably switched from v1 to v2 of our API client which was a major rewrite.
