### ISSUE TITLE
Error completing request [url] https://betalabs.zendesk.com/api/v2/tickets.json [http method] GET

### ISSUE THREAD

**Issue by victormacedo** [zendesk/zendesk_api_client_php#206]
When I utilize the method "tickets()->findAll()" exactly like the example in readme, this exception returns:

Error completing request [url] https://betalabs.zendesk.com/api/v2/tickets.json [http method] GET

My code sample:
$zendesk = new ZendeskAPI($subdominio, $usuario);
$zendesk->setAuth('basic', ['username' => $usuario, 'token' => $senha]);

$tickets = $zendesk->tickets()->findAll();

When I try authenticate with HTTP configurations (with Scheme = "HTTP" AND Port = "80") (because I was making test in my local environment), this exception returns:

Client error response [url] http://betalabs.zendesk.com/api/v2/tickets/recent.json [http method] GET [status code] 400 [reason phrase] Bad Request [details] This is an HTTPS only API

How to proceed?

Waiting for answers,
Victor

**Comment by RaFeNiX** [comment]
Hey,

Are you using token or user password?

Em 07/10/2015 18:13, Victor Macedo de Moura <notifications@github.com> escreveu:
When I utilize the method "tickets()->findAll()" exactly like the example in readme, this exception returns:

Error completing request [url] https://betalabs.zendesk.com/api/v2/tickets.json [http method] GET

My code sample:
$zendesk = new ZendeskAPI($subdominio, $usuario);
$zendesk->setAuth('basic', ['username' => $usuario, 'token' => $senha]);

$tickets = $zendesk->tickets()->findAll();

When I try authenticate with HTTP configurations (with Scheme = "HTTP" AND Port = "80") (because I was making test in my local environment), this exception returns:

Client error response [url] http://betalabs.zendesk.com/api/v2/tickets/recent.json [http method] GET [status code] 400 [reason phrase] Bad Request [details] This is an HTTPS only API

How to proceed?

Waiting for answers,
Victor

---
Reply to this email directly or view it on GitHub:
https://github.com/zendesk/zendesk_api_client_php/issues/206

**Comment by miogalang** [comment]
Hi Victor,

Yes you can authenticate with Zendesk using http if you are using localhost but when you make the actual request to the endpoints you have to use the https. 

Please do note that once you move this to an address other than localhost you will need https to authenticate with the API as well.

So when constructing the client for making API calls please use https as the scheme. The Zendesk API for security reasons has to use https.

Hopefully this helps.

Thanks,

Mio

**Comment by victormacedo** [comment]
@RaFeNiX token.

@miogalang thanks for the explication. I applied a verification to use HTTP or HTTPS in correct environment. But unfortunately not resolved my problem. I try HTTP and HTTPS but the exceptions block me to continue. How can I fix them? Is better downgrade of api's version?

**Comment by miogalang** [comment]
Hi @victormacedo,

From the code snippet I am unable to say why exactly this is throwing an error for you. But from the error, what I can tell you is that https should ALWAYS be used even when calling the API from a local environment. The API will block any calls that are not https.

so you should be hitting https://betalabs.zendesk.com/api/v2/tickets/recent.json instead of http://betalabs.zendesk.com/api/v2/tickets/recent.json

Just to see add more context, you can see https://github.com/zendesk/zendesk_api_client_php/blob/master/samples/getTickets.php with a nice example.

Any additional details would also help me help you figure out what is going wrong.

Thanks,

Mio
