### ISSUE TITLE
Error completing request [url] https://my22.zendesk.com/api/v2/tickets.json [http method] GET [body]

### ISSUE THREAD

**Issue by undentifiedkc** [zendesk/zendesk_api_client_php#248]
Hi, I was using the this API on **localhost** to try retrieving data, but error encounter after i fill in the credential.

Please find below for the error.

Uncaught exception 'Zendesk\API\Exceptions\ApiResponseException' 
with message 'Error completing request [url] https://my22.zendesk.com/api/v2/tickets.json [http method] GET [body] ' 
in C:\xampp2\htdocs\testing\zendesk_api_client_php-master\src\Zendesk\API\Http.php:89 
Stack trace: 
    #0 C:\xampp2\htdocs\testing\zendesk_api_client_php-master\src\Zendesk\API\HttpClient.php(400): Zendesk\API\Http::send(Object(Zendesk\API\HttpClient), 'tickets.json', Array) 
    #1 C:\xampp2\htdocs\testing\zendesk_api_client_php-master\src\Zendesk\API\Traits\Resource\FindAll.php(34): Zendesk\API\HttpClient->get('tickets.json', Array) 
    #2 C:\xampp2\htdocs\testing\zendesk_api_client_php-master\samples\getTickets.php(16): Zendesk\API\Resources\Core\Tickets->findAll() #3 {main} thrown in C:\xampp2\htdocs\testing\zendesk_api_client_php-master\src\Zendesk\API\Http.php on line 89

I have already enable token access in the domain > settings > API and copy the token from there.

**Comment by joseconsador** [comment]
@undentifiedkc Could you paste the code that you use here?

**Comment by julzpalomiano** [comment]
same issue as mine..

**Comment by joseconsador** [comment]
@julzpalomiano @undentifiedkc Can you catch the exception and dump the response here? Thanks.

**Comment by samgavinio** [comment]
For any one still experiencing this issue, this is often due to a curl misconfiguration in your host machine. We've made a change to this client's exception handling which should give you more context about the ApiResponseException you are getting.

Please update to at least v2.1.10 and inspect the context of the exception, as it should help you better debug the issue with your curl set-up.

As this is once of those older issues, we'll be closing this.
