### ISSUE TITLE
zendesk/zendesk_api_client_php contains .git and .gitignore

### ISSUE THREAD

**Issue by placeposition** [zendesk/zendesk_api_client_php#279]
I just installed with composer and this directory contains another .git directory which makes a mess of my parent application .git

**Comment by placeposition** [comment]
/vendor/zendesk/zendesk_api_client_php

**Comment by victoriafrench** [comment]
Composer is bringing down a file structure that contains a .git folder. This causes git to refuse to check in the files. The .git should never be distributed under any circumstances, they are per developer machine. Even after removing the .git there are still issues with committing and we are investigating.

**Comment by karl-casas777** [comment]
@placeposition @victoriafrench  I bet the you installed the package in `dev-master` version. Any composer package installed in a `dev-master` version will contain the .git folder because it assumes you want to contribute to the package. Installing the release tags instead will not include the .git folder.

**Comment by miogalang** [comment]
Please use the version tags for a more stable experience. Closing this issue.

**Comment by victoriafrench** [comment]
Perhaps you should consider updating your readme to explicitly state how to consume the project instead of how to contribute to it. Neither scenario is appropriately documented. On my end it won't matter much, I convinced my client to abandon this integration. I will also reiterate that there is NEVER a reason to ship a `.git` directory... ever. period.

**Comment by kcasas** [comment]
@victoriafrench You are right that's one of the reason why dev-master is not encouraged. Do know we don't intend for this behaviour. This happens with every composer dependency that has dev-master on it, not just this. I do hope you keep supporting this integration.

**Comment by miogalang** [comment]
Hi @victoriafrench 

I agree with you. This is default behaviour of composer for the master branch though and really there is nothing we can do about it.

What I would suggest is to install the library using the command

`composer require zendesk/zendesk_api_client_php` as this will update your composer.json automatically with the latest version.

This will also add the integration in your vendor folder without the git.

Thank you for the feedback we will be updating the readme in the next few days with this change in install instructions. 

Please let us know if there is anything else we can help you with.
