### ISSUE TITLE
Preserve line breaks 

### ISSUE THREAD

**Issue by zauan** [zendesk/zendesk_api_client_php#307]
Hi there, 

I'm using this api wrapper and i noticed that the line breaks aren't preserved when posting tickets/comments. Is there something i'm missing ?

Best regards,
Stefan

**Comment by kcasas** [comment]
Hello there,

I've used our examples and new lines works fine. Also tested using a form with textarea and let it submit through post request and it still works. Can you tell me about how you used our the api?

**Comment by zauan** [comment]
Hi,

We've made some more investigations and it seems to be working ok when using 'body', however, the lines are not preserved when using 'html_body'.

I know this feature is not oficially supported ( as there is no official documentation about it ), however, i've found this field in the following thread : https://support.zendesk.com/hc/en-us/community/posts/203454826-API-ticket-update-Is-html-body-an-allowable-key-to-update-

**Comment by joseconsador** [comment]
Hi, 

Since this method is undocumented, I'd exercise caution when using it; it may not be supported if something goes wrong. Rest assured - our documentation team is working to get this updated ASAP. You can subscribe to [API Updates](https://help.zendesk.com/hc/en-us/sections/206360887-API-updates) for when this gets a proper documentation.

Joms
