### ISSUE TITLE
HttpClient::VERSION is stale

### ISSUE THREAD

**Issue by dexen** [zendesk/zendesk_api_client_php#312]
According to commit history, const HttpClient::VERSION was not uploaded in the last several releases.
Let's use the 'VERSION' file for version information.

Pull request: #313

**Comment by samgavinio** [comment]
Our bad, the class constant hasn't been updated during recent version bumps.

We decided to stick with the class constant since reading the filesystem every time for the version seems like unnecessary overhead. We've been updating the stale version now and will make sure to keep it updated.

Thanks.
