### ISSUE TITLE
DatabaseConflict

### ISSUE THREAD

**Issue by vetheslav** [zendesk/zendesk_api_client_php#314]
Hello!
Sometimes I have this error:
Client error: `PUT https://unetby.zendesk.com/api/v2/tickets/121123.json` resulted in a `409 Conflict` response:
{"error":"DatabaseConflict","description":"Database collision"}
How to fix it?

Sentry error: https://sentry.io/share/issue/3134373436332e323335363337373835/

**Comment by jmramos02** [comment]
Hi @vetheslav Generally we throw 409 errors when data being created or updated already exists on a unique field. Can we know the payload of your request?

Thanks!

**Comment by vetheslav** [comment]
Hello, @jmramos02. See attach:
![2017-03-16 16 37 33](https://cloud.githubusercontent.com/assets/17473642/23998739/1419ad7a-0a67-11e7-9cdb-f7c6b72161bf.png)

**Comment by samgavinio** [comment]
@vetheslav I dug up your logs for one instance of a 409 from a PUT request, for: https://unetby.zendesk.com//api/v2/tickets/122262.json

```
 Parameters: {"ticket"=>{"custom_fields"=>{"32755089"=>"48", "25108075"=>"????????????????"}, "comment"=>{"body"=>"???????????? ??????????????????", "public"=>false, "uploads"=>["3ceF9jj1fwKoSZWIyY4pbk3tn"]}}, "id"=>"122262"}
```

dated March 22nd 2017, 04:36:20.675. It appears that the API is trying to reinsert the ticket field `32755089` into the database. Can you post here how this ticket field is configured from your zendesk account? You can see this in `Admin > Ticket Fields`.

In any case, this isn't an issue with this PHP Client. I'll try to help you out here but if there is in fact an issue with the API it's best to open a zendesk ticket so that zendesk support can take a look at it. You can try issuing standard curl requests to isolate the client from this issue.

**Comment by vetheslav** [comment]
@samgavinio Yes, here you can see the configuration of the field:
![2017-03-29 11 32 47](https://cloud.githubusercontent.com/assets/17473642/24445706/8d3d536c-1473-11e7-91b1-b8750f9fc76e.png)

Concerning writing zendesk ticket to zendesk support, let's see, maybe we can do this ourselves. If we don't coup with it, then I will ask the zendesk support

**Comment by samgavinio** [comment]
Doesn't look like there is anything special with your ticket custom field configuration or your ticket PUT payload. 

Just to close on this, generally the zendesk rest API will throw a 409 when there is a uniqueness constraint violation. Ensure that your application is not sending the same ticket update request multiple times in parallel as this may potentially cause collision problems for some of those requests. 

Since this is not an issue with this client itself I'm going to have close this issue. Should you continue to experience 409 issues, I would advise that you open a ticket for the API team to get support for your problem.

https://support.zendesk.com/hc/en-us/requests/new?ticket_form_id=253538
