### ISSUE TITLE
Sample paths aren't accurate when installing with composer

### ISSUE THREAD

**Issue by coreygans** [zendesk/zendesk_api_client_php#318]
1. Setup a directory called zendesk
2. Run the composer install: 
`composer require zendesk/zendesk_api_client_php `
3. The folder structure will be: zendesk/vendor/zendesk/zendesk_api_client_php/samples/tickets to get to a sample createTicket.php example
4. Within the createTicket.php example, the include is the following:
`include("../../vendor/autoload.php");`

When you actually need to have it go to:
`include("../../../../../vendor/autoload.php");`

I created this as an issue as opposed to making changes to the individual file as I suspect I'm either missing something or this is a systemic issue that would be addressed outside of a single file.

**Comment by joseconsador** [comment]
@coreygans I believe the samples were meant to work if the repo is cloned directly. Sorry for any confusion.

**Comment by coreygans** [comment]
@joseconsador but the vendor directory doesn't exist when you clone the repo. It is only created when you install with composer.

**Comment by samgavinio** [comment]
Hi corey, you are correct that the vendor directory is only created when you do run `composer install/update`. You are required to run composer either way to use the client because the dependencies it needs are only going to be available after a composer install.

In any case, the samples are generally there as a guide for you to get going. You may need to update the path to the correct autoload file depending on how the package is installed. In this case, the relative path only points to the appropriate file after doing a git clone and a composer install. 

1. git clone https://github.com/zendesk/zendesk_api_client_php
2. cd into the repo directory, run `composer install` to download the deps
3. this should have generated a vendor/autoload.php file which should be in the correct relative path for the samples.

The readme could have made it clearer though that this is the case. Closing this one for now, we'll look into improving the docs about the samples if more confusion arises from them. Thanks!
