### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Zendesk\API\HttpClient' not found

### ISSUE THREAD

**Issue by shaliniinfris** [zendesk/zendesk_api_client_php#329]
Hello,

After installing the composer using below script 

// load Composer
require 'vendor/autoload.php';

use Zendesk\API\HttpClient as ZendeskAPI;

$subdomain = "subdomain";
$username  = "email@example.com"; // replace this with your registered email
$token     = "6wiIBWbGkBMo1mRDMuVwkw1EPsNkeUj95PIz2akv"; // replace this with your token

$client = new ZendeskAPI($subdomain);
$client->setAuth('basic', ['username' => $username, 'token' => $token]);

I am facing this error - 
Fatal error: Uncaught Error: Class 'Zendesk\API\HttpClient' not found in index.php:54 Stack trace: #0 {main} thrown in index.php on line 54

On my localhost using xampp got below error -

Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `GET https://od-basehelp.zendesk.com/api/v2/tickets.json` resulted in a `401 Unauthorized` response: {"error":"Couldn't authenticate you"} ' in D:\xampp\htdocs\projects\zendesk\zendesk_api_client_php-master\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:111 Stack trace: #0 D:\xampp\htdocs\projects\zendesk\zendesk_api_client_php-master\vendor\guzzlehttp\guzzle\src\Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 D:\xampp\htdocs\projects\zendesk\zendesk_api_client_php-master\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 D:\xampp\htdocs\projects\zendesk\zendesk_api_client_php-master\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 D:\xampp\htdocs\projects\zendes in D:\xampp\htdocs\projects\zendesk\zendesk_api_client_php-master\vendor\zendesk\zendesk_api_client_php\src\Zendesk\API\Http.php on line 92

**Comment by samgavinio** [comment]
@shaliniinfris you are experiencing two different issues.

1. Fatal error: Uncaught Error: Class 'Zendesk\API\HttpClient' not found - means that you have either not configured your composer autoloader correctly or have not run composer install yet.

2. Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: GET https://od-basehelp.zendesk.com/api/v2/tickets.json resulted in a 401 Unauthorized - this one means that the client can now be autoloaded correctly but you are getting this error because you have not set your zendesk credentials yet. Look at https://github.com/zendesk/zendesk_api_client_php#configuration, make sure to update the $subdomain, $token and $username to the one for your zendesk account. If you are unsure how to generate your API token, refer to this helpcenter article: https://support.zendesk.com/hc/en-us/articles/226022787-Generating-a-new-API-token-
