### ISSUE TITLE
Randomly getting cURL error 35: Unknown SSL protocol error

### ISSUE THREAD

**Issue by LionelLaffineur** [zendesk/zendesk_api_client_php#334]
Dears,

I'm randomly getting the following error when accessing Zendesk with this API client:
`cURL error 35: Unknown SSL protocol error in connection to mysubdomain.zendesk.com:443  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

It happens randomly whatever function of the API I use, **in the SSL handshake process**.

Does anyone already have encountered the same error ?  And if true, what is the fix ?

Thanks in advance,
Lionel

**Comment by samgavinio** [comment]
@LionelLaffineur could you see what version of curl (openssl) you are getting? We've been having reports of SSL issues for older versions of curl.

**Comment by arkrahl** [comment]
@LionelLaffineur We are encountering the same issue. Concerns 70-80 ticket creations a day. On June 30th even more than 700 ticket creations.
<img width="1264" alt="screen shot 2017-06-06 at 18 54 12" src="https://user-images.githubusercontent.com/5276306/26842305-a1e059f4-4aec-11e7-949f-a99b8f5e45cc.png">

**Comment by LionelLaffineur** [comment]
@samgavinio We are using the following version of cURL:
```
Array 
( 
[version_number] => 468480 
[age] => 3 
[features] => 182173 
[ssl_version_number] => 0 
[version] => 7.38.0 
[host] => x86_64-pc-linux-gnu 
[ssl_version] => OpenSSL/1.0.1t 
[libz_version] => 1.2.8 
[protocols] => Array 
( 
[0] => dict 
[1] => file 
[2] => ftp 
[3] => ftps 
[4] => gopher 
[5] => http 
[6] => https 
[7] => imap 
[8] => imaps 
[9] => ldap 
[10] => ldaps 
[11] => pop3 
[12] => pop3s 
[13] => rtmp 
[14] => rtsp 
[15] => scp 
[16] => sftp 
[17] => smtp 
[18] => smtps 
[19] => telnet 
[20] => tftp 
)
)
```
What is strange to me is that it is random; if cURL would be the problem, why wouldn't it be always ?
I'm really interested understanding it, thanks in advance for helping us.

**Comment by LionelLaffineur** [comment]
Hi @arkrahl, I'm sad you are having problems but am also happy not to be alone with that issue!
What kind of answer did you get from Zendesk support ?
And did you find any way to solve / bypass the problem ?

**Comment by cyrnetix** [comment]
We have exactly the same issue for several months randomly every day.

curl 7.54.0 (x86_64-redhat-linux-gnu) libcurl/7.54.0 OpenSSL/1.0.1e zlib/1.2.3 c-ares/1.12.0 libssh2/1.8.0 nghttp2/1.6.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy Metalink

**Comment by SamanthaAdrichem** [comment]
It's very random indeed. 90% of all calls do seem to function

The exact error we're getting is: 

> cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to subdomain.zendesk.com:443 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

our version is what cyrnetix said

**Comment by kcasas** [comment]
We believe there is an intermittent problem with our server's ssl implementation. The ops team are already investigating the issue. Will get back to you if any progress was made.

**Comment by LionelLaffineur** [comment]
Some more info: I have ran a simple test on a virtual machine running the latest Debian and I have been able to reproduce the issue 5 times on a test of about 10 hours (1 thread querying Zendesk in a loop).

Here are the complete specs: Debian 9.0, PHP 7.0.19-1, CURL [version_number] => 472065 [features] => 4179869 [version] => 7.52.1 [ssl_version] => OpenSSL/1.0.2k [libz_version] => 1.2.8.

**Comment by natelloyd** [comment]
Also experiencing this.
Centos6
curl 7.50.3
php 5.6.30
OpenSSL 1.0.1e-fips 11 Feb 2013
built on: Wed Mar 22 21:43:28 UTC 2017

**Comment by samgavinio** [comment]
Hi  @cyrnetix, @SamanthaAdrichem, @natelloyd can you guys please  have a look what pod your zendesk is in and email it to me at sgavinio@zendesk.com? So far evidence suggests that this is a network issue affecting zendesk instances in certain pods and it would help to verify this if you can let us know what pods you are in. I already have @LionelLaffineur's and @arkrahl's.

If you are unsure where to find what your pod is, please refer to the "How do I learn what Pod I am on"? in https://support.zendesk.com/hc/en-us/articles/219614808-What-is-a-Pod-#How-do-I-learn-what-Pod-I-am-on?

**Comment by SamanthaAdrichem** [comment]
@samgavinio 

It took a while but our (@cyrnetix and me) system is hosted in Pod 3 https://status.zendesk.com/#daisycon

**Comment by samgavinio** [comment]
Hi all, circling back on this again and just providing some updates.  This SSL handshake issue with the Zendesk API is intermittently occurring even without using the PHP client. As such, discussions with resolution of the intermittent SSL issue itself is best coursed through a support ticket with Zendesk. Most of the reporters here already have open tickets regarding the issue which is great, I will be creating one for those who emailed me previously and do not have a ticket yet.

As for the PHP API client here, we are working on adding baked-in retry support in to the client to mitigate these kinds intermittent failures. We'll be updating you as soon as we get that released. Thanks.

**Comment by kcasas** [comment]
Hi all, We've released a minor update [zendesk/zendesk_api_client_php:v2.2.0](https://github.com/zendesk/zendesk_api_client_php/releases/tag/v2.2.0) that hopefully mitigates the effect of the intermittent ssl issues. The new client now retries requests that failed due to ssl problem. The main issue with our servers will still be fixed.

**Comment by christopheg** [comment]
Dear Zendesk,

Let me state that what is implemented here is not what we can expect from a company like Zendesk. Sure, your issue here is closed and people using this client will be tranquilized because they won't notice this problem anymore.
But you seem to miss the point here that there is a problem on the server infrastructure for a very long time already which you don't want to fix.
Accept wasting our time with your support ping-pong, you are wasting precious time of many other developer using your API.
Have a look at some other tickets for other API clients:
https://github.com/zendesk/zendesk_api_client_rb/issues/325
https://github.com/facetoe/zenpy/issues/51

They all need to go through this very time-consuming process:
SSL problem -> Problem at Zendesk? -> Ticket to Zendesk -> No solution -> Retry mechanism in client -> performance regression

Second, I have the feeling that by closing this ticket you want to prevent others from sharing their experiences in public, something which seems to be very sensitive at Zendesk support. Our 35 messages long support request only started to move once this ticket was opened by my colleague:

> I just heard back from one of our Dev engineers and they have let me know that since raising this ticket we have been monitoring the behavior and we are seeing something that might be on our end and we're no longer so sure that this has to do only with the version of cURL and openssl, though those factors might be still be related.

This was 3 months after opening the ticket...

Finally to fix this problem, I want to reach out to you by offering our help. I'm pretty sure our server infrastructure team can help you solving this problem. Feel free to get in contact with me!

Warm regards,
Christophe

**Comment by eddieMicroblink** [comment]
Two years later and the issue still hasn't been resolved..

**Comment by franklingu** [comment]
based on what I experienced and [ref](https://www.wormly.com/answers/sid/142/topicid/19#:~:text=This%20issue%20is%20often%20caused,failing%20to%20correctly%20negotiate%20TLSv1.&text=When%20you%20see%20this%20error,likely%20to%20instead%20require%20TLSv1.)

I believe it is the problem with the server
