### ISSUE TITLE
Expose createOrUpdate for organizations

### ISSUE THREAD

**Issue by MatTheCat** [zendesk/zendesk_api_client_php#370]
https://developer.zendesk.com/rest_api/docs/core/organizations#create-or-update-organization

But the SDK does not provide this route.

**Comment by marnickmenting** [comment]
I see a pull request is closed for this one, but it seems the method is not available at the Organizations resource. I even tried to switch to 'dev-master' in composer.json but I don't see the method in the source. Am i doing something wrong?

**Comment by m-norii** [comment]
I wonder why PR #407 is closed.
This issue is not resolved latest version.

[added createOrUpdate method to Organizations resource · roncodes/zendesk\_api\_client\_php@665e6ac](https://github.com/roncodes/zendesk_api_client_php/commit/665e6ac1618cc75f9f86604c2f093c409ab907f9)
This change looks good to me.

**Comment by ecoologic** [comment]
summarily closed due to staleness.
