### ISSUE TITLE
Array to string conversion error

### ISSUE THREAD

**Issue by ghost** [zendesk/zendesk_api_client_php#465]
`\Zendesk\API\Debug::__toString()`

`$this->lastResponseHeaders` and `$this->lastRequestHeaders` are arrays so method fails.

**Comment by mtk3d** [comment]
Hi, of course 😄 
The problem is when I'm trying to cast Debug object to string. Debug object has `_toString()` magic method, so I should be able to cast it to a string like this:

```PHP
$debugContent = (string) $client->getDebug();
```

The problem is, that inside `_toString()` there is a concatination of `lastResponseHeaders` param with a string. In this case, PHP is trying to cast it to the string also, but `lastResponseHeaders` contains an array of headers, and it's not possible to directly cast it to a string.

**Comment by ecoologic** [comment]
Just a little update that I don't have an update yet, but we haven't forgotten, please bear with us. This doesn't sound blocking, but let us know if it's a big issue.

**Comment by ecoologic** [comment]
@mtk3d  - can you take a look at the small PR above, please?
